import type { Word } from '@/typings'

export const exampleWords: Word[] = [
  {
    name: 'hello',
    trans: ['你好', '哈啰'],
    usphone: 'həˈloʊ',
    ukphone: 'həˈləʊ',
  },
  {
    name: 'world',
    trans: ['世界', '地球'],
    usphone: 'wɜrld',
    ukphone: 'wɜːld',
  },
  {
    name: 'example',
    trans: ['例子', '示例'],
    usphone: 'ɪɡˈzæmpəl',
    ukphone: 'ɪɡˈzæmpəl',
  },
]

export const llmWords: Word[] = [
  { name: 'algorithm', trans: ['算法'], usphone: "'ælɡərɪðəm", ukphone: "'ælɡərɪðəm" },
  { name: 'artificial', trans: ['人工的', '人造的'], usphone: ",ɑrtɪ'fɪʃl", ukphone: ",ɑːtɪ'fɪʃl" },
  { name: 'intelligence', trans: ['智能', '智力'], usphone: "ɪn'telɪdʒəns", ukphone: "ɪn'telɪdʒəns" },
  { name: 'machine', trans: ['机器', '机械'], usphone: "mə'ʃin", ukphone: "mə'ʃiːn" },
  { name: 'learning', trans: ['学习', '学问'], usphone: "'lɜrnɪŋ", ukphone: "'lɜːnɪŋ" },
  { name: 'neural', trans: ['神经的', '神经系统的'], usphone: "'nʊrəl", ukphone: "'njʊərəl" },
  { name: 'network', trans: ['网络', '网状系统'], usphone: "'netwɜrk", ukphone: "'netwɜːk" },
  { name: 'model', trans: ['模型', '模式'], usphone: "'mɑdl", ukphone: "'mɒdl" },
  { name: 'transformer', trans: ['变换器', '变压器'], usphone: "træns'fɔrmər", ukphone: "træns'fɔːmə" },
  { name: 'attention', trans: ['注意力', '关注'], usphone: "ə'tenʃn", ukphone: "ə'tenʃn" },
  { name: 'embedding', trans: ['嵌入', '嵌入向量'], usphone: "ɪm'bedɪŋ", ukphone: "ɪm'bedɪŋ" },
  { name: 'token', trans: ['标记', '令牌'], usphone: "'toʊkən", ukphone: "'təʊkən" },
  { name: 'prompt', trans: ['提示', '提示词'], usphone: 'prɑmpt', ukphone: 'prɒmpt' },
  { name: 'generation', trans: ['生成', '产生'], usphone: ",dʒenə'reɪʃn", ukphone: ",dʒenə'reɪʃn" },
  { name: 'inference', trans: ['推理', '推断'], usphone: "'ɪnfərəns", ukphone: "'ɪnfərəns" },
  { name: 'training', trans: ['训练', '培训'], usphone: "'treɪnɪŋ", ukphone: "'treɪnɪŋ" },
  { name: 'fine-tuning', trans: ['微调', '精细调整'], usphone: "faɪn 'tunɪŋ", ukphone: "faɪn 'tjuːnɪŋ" },
  { name: 'parameter', trans: ['参数', '参量'], usphone: "pə'ræmɪtər", ukphone: "pə'ræmɪtə" },
  { name: 'dataset', trans: ['数据集', '数据集合'], usphone: "'deɪtəset", ukphone: "'deɪtəset" },
  { name: 'supervised', trans: ['监督的', '有监督的'], usphone: "'supəvaɪzd", ukphone: "'suːpəvaɪzd" },
  { name: 'unsupervised', trans: ['无监督的', '非监督的'], usphone: ",ʌn'supəvaɪzd", ukphone: ",ʌn'suːpəvaɪzd" },
  { name: 'reinforcement', trans: ['强化', '加强'], usphone: ",riɪn'fɔrsmənt", ukphone: ",riːɪn'fɔːsmənt" },
  { name: 'gradient', trans: ['梯度', '斜率'], usphone: "'ɡreɪdiənt", ukphone: "'ɡreɪdiənt" },
  { name: 'backpropagation', trans: ['反向传播', '反向传播算法'], usphone: ",bækprɑpə'ɡeɪʃn", ukphone: ",bækprɒpə'ɡeɪʃn" },
  { name: 'optimization', trans: ['优化', '最优化'], usphone: ",ɑptɪmɪ'zeɪʃn", ukphone: ",ɒptɪmaɪ'zeɪʃn" },
  { name: 'loss', trans: ['损失', '损失函数'], usphone: 'lɔs', ukphone: 'lɒs' },
  { name: 'function', trans: ['函数', '功能'], usphone: "'fʌŋkʃn", ukphone: "'fʌŋkʃn" },
  { name: 'epoch', trans: ['轮次', '训练轮次'], usphone: "'epək", ukphone: "'iːpɒk" },
  { name: 'batch', trans: ['批次', '批量'], usphone: 'bætʃ', ukphone: 'bætʃ' },
  { name: 'layer', trans: ['层', '层次'], usphone: "'leɪər", ukphone: "'leɪə" },
  { name: 'activation', trans: ['激活', '激活函数'], usphone: ",æktɪ'veɪʃn", ukphone: ",æktɪ'veɪʃn" },
  { name: 'weight', trans: ['权重', '重量'], usphone: 'weɪt', ukphone: 'weɪt' },
  { name: 'bias', trans: ['偏置', '偏见'], usphone: "'baɪəs", ukphone: "'baɪəs" },
  { name: 'dropout', trans: ['丢弃', 'dropout层'], usphone: "'drɑpaʊt", ukphone: "'drɒpaʊt" },
  { name: 'regularization', trans: ['正则化', '规则化'], usphone: ",reɡjələrɪ'zeɪʃn", ukphone: ",reɡjʊləraɪ'zeɪʃn" },
  { name: 'overfitting', trans: ['过拟合', '过度拟合'], usphone: ",oʊvər'fɪtɪŋ", ukphone: ",əʊvə'fɪtɪŋ" },
  { name: 'underfitting', trans: ['欠拟合', '拟合不足'], usphone: ",ʌndər'fɪtɪŋ", ukphone: ",ʌndə'fɪtɪŋ" },
  { name: 'validation', trans: ['验证', '校验'], usphone: ",vælɪ'deɪʃn", ukphone: ",vælɪ'deɪʃn" },
  { name: 'accuracy', trans: ['准确率', '精确度'], usphone: "'ækjərəsi", ukphone: "'ækjʊrəsi" },
  { name: 'precision', trans: ['精确率', '精度'], usphone: "prɪ'sɪʒn", ukphone: "prɪ'sɪʒn" },
  { name: 'recall', trans: ['召回率', '回忆'], usphone: "rɪ'kɔl", ukphone: "rɪ'kɔːl" },
  { name: 'f1-score', trans: ['F1分数', 'F1得分'], usphone: 'ef wʌn skɔr', ukphone: 'ef wʌn skɔː' },
  { name: 'benchmark', trans: ['基准', '基准测试'], usphone: "'bentʃmɑrk", ukphone: "'bentʃmɑːk" },
  { name: 'evaluation', trans: ['评估', '评价'], usphone: "ɪ,vælju'eɪʃn", ukphone: "ɪ,vælju'eɪʃn" },
  { name: 'metric', trans: ['指标', '度量'], usphone: "'metrɪk", ukphone: "'metrɪk" },
  { name: 'preprocessing', trans: ['预处理', '前处理'], usphone: ",pri'prɑsesɪŋ", ukphone: ",priː'prəʊsesɪŋ" },
  { name: 'normalization', trans: ['归一化', '标准化'], usphone: ",nɔrməlɪ'zeɪʃn", ukphone: ",nɔːməlaɪ'zeɪʃn" },
  { name: 'encoding', trans: ['编码', '编码方式'], usphone: "ɪn'koʊdɪŋ", ukphone: "ɪn'kəʊdɪŋ" },
  { name: 'decoding', trans: ['解码', '解码过程'], usphone: "dɪ'koʊdɪŋ", ukphone: "dɪ'kəʊdɪŋ" },
  { name: 'sequence', trans: ['序列', '顺序'], usphone: "'sikwəns", ukphone: "'siːkwəns" },
  { name: 'context', trans: ['上下文', '语境'], usphone: "'kɑntekst", ukphone: "'kɒntekst" },
  { name: 'semantic', trans: ['语义的', '语义学'], usphone: "sɪ'mæntɪk", ukphone: "sɪ'mæntɪk" },
  { name: 'syntax', trans: ['语法', '句法'], usphone: "'sɪntæks", ukphone: "'sɪntæks" },
  { name: 'sentence', trans: ['句子', '语句'], usphone: "'sentəns", ukphone: "'sentəns" },
  { name: 'vocabulary', trans: ['词汇', '词汇表'], usphone: "voʊ'kæbjə,leri", ukphone: "və'kæbjʊləri" },
  { name: 'corpus', trans: ['语料库', '语料'], usphone: "'kɔrpəs", ukphone: "'kɔːpəs" },
  { name: 'annotation', trans: ['标注', '注释'], usphone: ",ænə'teɪʃn", ukphone: ",ænə'teɪʃn" },
  { name: 'label', trans: ['标签', '标记'], usphone: "'leɪbl", ukphone: "'leɪbl" },
  { name: 'feature', trans: ['特征', '特点'], usphone: "'fitʃər", ukphone: "'fiːtʃə" },
  { name: 'extraction', trans: ['提取', '抽取'], usphone: "ɪk'strækʃn", ukphone: "ɪk'strækʃn" },
  { name: 'classification', trans: ['分类', '分类任务'], usphone: ",klæsɪfɪ'keɪʃn", ukphone: ",klæsɪfɪ'keɪʃn" },
  { name: 'regression', trans: ['回归', '回归分析'], usphone: "rɪ'ɡreʃn", ukphone: "rɪ'ɡreʃn" },
  { name: 'clustering', trans: ['聚类', '分群'], usphone: "'klʌstərɪŋ", ukphone: "'klʌstərɪŋ" },
  { name: 'dimensionality', trans: ['维度', '维数'], usphone: "dɪ,menʃə'nælɪti", ukphone: "dɪ,menʃə'nælɪti" },
  { name: 'reduction', trans: ['降维', '减少'], usphone: "rɪ'dʌkʃn", ukphone: "rɪ'dʌkʃn" },
  { name: 'pretraining', trans: ['预训练', '预训练过程'], usphone: ",pri'treɪnɪŋ", ukphone: ",priː'treɪnɪŋ" },
  { name: 'transfer', trans: ['迁移', '转移'], usphone: "træns'fɜr", ukphone: "træns'fɜː" },
  { name: 'adaptation', trans: ['适应', '适配'], usphone: ",ædæp'teɪʃn", ukphone: ",ædæp'teɪʃn" },
  { name: 'multimodal', trans: ['多模态', '多模式'], usphone: ",mʌlti'moʊdl", ukphone: ",mʌlti'məʊdl" },
  { name: 'vision', trans: ['视觉', '视力'], usphone: "'vɪʒn", ukphone: "'vɪʒn" },
  { name: 'speech', trans: ['语音', '讲话'], usphone: 'spitʃ', ukphone: 'spiːtʃ' },
  { name: 'recognition', trans: ['识别', '认识'], usphone: ",rekəɡ'nɪʃn", ukphone: ",rekəɡ'nɪʃn" },
  { name: 'summarization', trans: ['摘要', '总结'], usphone: ",sʌmərɪ'zeɪʃn", ukphone: ",sʌməraɪ'zeɪʃn" },
  { name: 'translation', trans: ['翻译', '转换'], usphone: "træns'leɪʃn", ukphone: "træns'leɪʃn" },
  { name: 'question', trans: ['问题', '疑问'], usphone: "'kwestʃən", ukphone: "'kwestʃən" },
  { name: 'answering', trans: ['问答', '回答'], usphone: "'ænsərɪŋ", ukphone: "'ɑːnsərɪŋ" },
  { name: 'conversation', trans: ['对话', '会话'], usphone: ",kɑnvər'seɪʃn", ukphone: ",kɒnvə'seɪʃn" },
  { name: 'chatbot', trans: ['聊天机器人', '对话机器人'], usphone: "'tʃætbɑt", ukphone: "'tʃætbɒt" },
  { name: 'assistant', trans: ['助手', '助理'], usphone: "ə'sɪstənt", ukphone: "ə'sɪstənt" },
  { name: 'agent', trans: ['代理', '智能体'], usphone: "'eɪdʒənt", ukphone: "'eɪdʒənt" },
  { name: 'reasoning', trans: ['推理', '论证'], usphone: "'rizənɪŋ", ukphone: "'riːzənɪŋ" },
  { name: 'knowledge', trans: ['知识', '学问'], usphone: "'nɑlɪdʒ", ukphone: "'nɒlɪdʒ" },
  { name: 'graph', trans: ['图', '图表'], usphone: 'ɡræf', ukphone: 'ɡrɑːf' },
  { name: 'knowledge-graph', trans: ['知识图谱', '知识图'], usphone: "'nɑlɪdʒ ɡræf", ukphone: "'nɒlɪdʒ ɡrɑːf" },
  { name: 'hallucination', trans: ['幻觉', '幻觉问题'], usphone: "hə,lusɪ'neɪʃn", ukphone: "hə,luːsɪ'neɪʃn" },
  { name: 'alignment', trans: ['对齐', '校准'], usphone: "ə'laɪnmənt", ukphone: "ə'laɪnmənt" },
  { name: 'safety', trans: ['安全性', '安全'], usphone: "'seɪfti", ukphone: "'seɪfti" },
  { name: 'ethics', trans: ['伦理', '道德'], usphone: "'eθɪks", ukphone: "'eθɪks" },
  { name: 'bias', trans: ['偏见', '偏差'], usphone: "'baɪəs", ukphone: "'baɪəs" },
  { name: 'fairness', trans: ['公平性', '公正'], usphone: "'fernes", ukphone: "'feənes" },
  { name: 'explainability', trans: ['可解释性', '可说明性'], usphone: "ɪk,spleɪnə'bɪlɪti", ukphone: "ɪk,spleɪnə'bɪlɪti" },
  { name: 'interpretability', trans: ['可解释性', '可理解性'], usphone: "ɪn,tɜrprɪtə'bɪlɪti", ukphone: "ɪn,tɜːprɪtə'bɪlɪti" },
  { name: 'robustness', trans: ['鲁棒性', '健壮性'], usphone: "roʊ'bʌstnes", ukphone: "rəʊ'bʌstnes" },
  { name: 'adversarial', trans: ['对抗的', '敌对的'], usphone: ",ædvər'seriəl", ukphone: ",ædvə'seriəl" },
  { name: 'attack', trans: ['攻击', '袭击'], usphone: "ə'tæk", ukphone: "ə'tæk" },
  { name: 'defense', trans: ['防御', '防护'], usphone: "dɪ'fens", ukphone: "dɪ'fens" },
  { name: 'privacy', trans: ['隐私', '私密性'], usphone: "'praɪvəsi", ukphone: "'prɪvəsi" },
  { name: 'federated', trans: ['联邦的', '联合的'], usphone: "'fedəreɪtɪd", ukphone: "'fedəreɪtɪd" },
  { name: 'differential', trans: ['差分', '差异'], usphone: ",dɪfə'renʃl", ukphone: ",dɪfə'renʃl" },
  { name: 'scalability', trans: ['可扩展性', '可伸缩性'], usphone: ",skeɪlə'bɪlɪti", ukphone: ",skeɪlə'bɪlɪti" },
  { name: 'efficiency', trans: ['效率', '效能'], usphone: "ɪ'fɪʃənsi", ukphone: "ɪ'fɪʃənsi" },
  { name: 'quantization', trans: ['量化', '量化技术'], usphone: ",kwɑntɪ'zeɪʃn", ukphone: ",kwɒntaɪ'zeɪʃn" },
  { name: 'pruning', trans: ['剪枝', '修剪'], usphone: "'prunɪŋ", ukphone: "'pruːnɪŋ" },
  { name: 'distillation', trans: ['蒸馏', '知识蒸馏'], usphone: ",dɪstɪ'leɪʃn", ukphone: ",dɪstɪ'leɪʃn" },
  { name: 'deployment', trans: ['部署', '配置'], usphone: "dɪ'plɔɪmənt", ukphone: "dɪ'plɔɪmənt" },
  { name: 'serving', trans: ['服务', '服务化'], usphone: "'sɜrvɪŋ", ukphone: "'sɜːvɪŋ" },
  { name: 'latency', trans: ['延迟', '延迟时间'], usphone: "'leɪtənsi", ukphone: "'leɪtənsi" },
  { name: 'throughput', trans: ['吞吐量', '处理量'], usphone: "'θrupʊt", ukphone: "'θruːpʊt" },
  { name: 'gpu', trans: ['GPU', '图形处理器'], usphone: ",dʒi pi 'ju", ukphone: ",dʒiː piː 'juː" },
  { name: 'tpu', trans: ['TPU', '张量处理单元'], usphone: ",ti pi 'ju", ukphone: ",tiː piː 'juː" },
  { name: 'compute', trans: ['计算', '计算资源'], usphone: "kəm'pjut", ukphone: "kəm'pjuːt" },
  { name: 'memory', trans: ['内存', '存储器'], usphone: "'meməri", ukphone: "'meməri" },
  { name: 'bandwidth', trans: ['带宽', '频宽'], usphone: "'bændwɪdθ", ukphone: "'bændwɪdθ" },
]
